### ISSUE TITLE
Sample project has bug in color selections

### ISSUE THREAD

**Issue by alphadon-chris** [bramerdaniel/ConsoLovers#5]
Daniel, 

   There is a bug when testing the color themes on the ConsoleMenuExplorer. To see it, follow these steps:

1. Debug ConsoleMenuExplorer from VS2015.
2. Select "Choose Color Theme"
3.  Choose "Blue"
4. Choose "Red"
5. Choose "Pink"
6. Choose "Crazy". Your screem will be 100% covered with an orange console with no way to resume. You must exit to recover from this. This is unexpected.

Thanks,
Chris (same as ats-ccochran)

**Comment by bramerdaniel** [comment]
Hi Chris,

Yes I know that bug, and I will not be able to fix it.
The problem is that if you use more than 16 different colors, there is no way to redefine the 17th color and map it to the ConsoleColors enum.

In the next version of my nuget package I will provice two different menus .
1. ColoredConsoleMenu using the System.Drawing.Colors 
2. ConsoleMenu using the ConsoleColors enum 

After that you can decide if you want to use the normal ConsoleMenu (then the bug will no longer occur)
or if you want the color support. 

In an normal application you will not give your user the ability to change the color, but you as developer will choose the colors you want => this will not cause an error when you do not user 17 different colors

Daniel
